version: "3.9"
services:
  app:
    build: .
    container_name: backend_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/backenddb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: backend_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
